[package]
name = "rs_2dplatformer_piston"
version = "0.1.0"
authors = ["Sugi <sugidaffection@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.131.0"
find_folder = "0.3.0"
fps_counter = "3.0.0"
